//! The other side of the game. Do not edit this file!
//!
//! The secret keeper is whoever picked the number. Your job as the guesser is to ask them
//! questions until you know what it is; their job is to answer honestly and to
//! keep count of how many questions you needed.
//!
//! There are two kinds. `SecretKeeper::human()` asks the person sitting at the
//! keyboard. `SecretKeeper::known(x)` already knows the number is x and answers
//! instantly, which is what lets the tests and the benchmark work.

use std::io;

/// Where the answers come from.
enum Source {
    Human,
    Known(u32),
}

pub struct SecretKeeper {
    source: Source,
    questions: u32,
    /// Numbers used as the secret in *earlier* games from the same dealer. The
    /// current secret is never in here.
    already_used: Vec<u32>,
}

impl SecretKeeper {
    /// A keeper who will ask the person at the keyboard.
    pub fn human() -> SecretKeeper {
        SecretKeeper {
            source: Source::Human,
            questions: 0,
            already_used: Vec::new(),
        }
    }

    /// A keeper who is holding the number you pass in, with no history behind it.
    pub fn known(number: u32) -> SecretKeeper {
        SecretKeeper {
            source: Source::Known(number),
            questions: 0,
            already_used: Vec::new(),
        }
    }

    /// Could the number still be `n`, given what you know? A number
    /// that was the secret in an earlier game cannot be the secret again.
    pub fn is_still_possible(&self, n: u32) -> bool {
        !self.already_used.contains(&n)
    }

    /// How many questions have been asked so far. This is the score.
    pub fn questions_asked(&self) -> u32 {
        self.questions
    }

    /// "Is your number exactly this?" True only on an exact match.
    pub fn ask_if_equal(&mut self, guess: u32) -> bool {
        self.questions += 1;
        match self.source {
            Source::Known(number) => number == guess,
            Source::Human => ask_human(&format!("Is your number equal to {guess}")),
        }
    }

    /// "Is your number bigger than this?" Doesn't give you equal or not equal.
    /// True means the secret > guess , false means secret <= guess.
    pub fn ask_if_greater(&mut self, guess: u32) -> bool {
        self.questions += 1;
        match self.source {
            Source::Known(number) => number > guess,
            Source::Human => ask_human(&format!("Is your number greater than {guess}")),
        }
    }
}

/// Put a yes or no question to the person at the keyboard.
fn ask_human(question: &str) -> bool {
    println!("{question} [y/n]? ");
    loop {
        let mut answer = String::new();
        io::stdin()
            .read_line(&mut answer)
            .expect("Failed to read line");

        match answer.trim() {
            "y" => return true,
            "n" => return false,
            _ => println!("Please type y for yes or n for no: "),
        }
    }
}

/// Deals out one game after another, never using the same secret twice.
///
/// You do not need to read this. `measure` uses it to start each round, and it is
/// what makes `is_still_possible` meaningful.
pub struct Dealer {
    min: u32,
    max: u32,
    used: Vec<u32>,
}

impl Dealer {
    pub fn new(min: u32, max: u32) -> Dealer {
        Dealer {
            min,
            max,
            used: Vec::new(),
        }
    }

    /// Start a new game. Picks a secret at random from the numbers not yet used,
    /// and hands you a keeper that remembers the ones that are gone.
    ///
    /// When every number has been the secret once, the deck is reshuffled and it
    /// starts over.
    pub fn deal(&mut self) -> SecretKeeper {
        if self.used.len() as u32 >= self.max - self.min {
            self.used.clear();
        }
        let number = loop {
            let candidate = rand::random_range(self.min..self.max);
            if !self.used.contains(&candidate) {
                break candidate;
            }
        };
        let keeper = SecretKeeper {
            source: Source::Known(number),
            questions: 0,
            already_used: self.used.clone(),
        };
        self.used.push(number);
        keeper
    }
}
