//! Do not edit this file.
//!
//! It records which release of the repo you have. When we push an update, this
//! number goes up, and the autograder uses it to tell you that there is work
//! waiting for you upstream.
#![allow(dead_code)]

/// Bumped by every staged release.
pub const STENCIL_VERSION: u32 = 2;
